language: python
python:
- '3.5'
dist: trusty
install:
- pip install s3cmd==2.0.2
- pip install delegator.py==0.1.1
script:
- python devtools/create_key_file.py
- python devtools/push-docs-to-s3.py
- rm keys.crt
after_success:
- echo "Website Updated"
env:
  global:
  - secure: jLfiAC9sMT0VL+gCq02cfi5wwLHm3XtPnnRgLfUvwnz8QdzshM3fchBxHWIbVFC76U/m0A76N9SSjUZQ17twKvcnsGuXeFvEAgoEJ1v9O2yRInufdu6PyOMBmGdhtCJAWKgpLaRjmgpSTwpGu+7yC0pXD2Uzs2rJV5Jq+a7g83e4gXkGL3erng4+5r9S0ysn/w5V7TMEAJluMHOz6jH7sFPFxxhoBUq6ANsIpYQSbpbZCb7bh9AbohvZ0rlUnz8dmrEZvwfWZ8OTWU3D1hpfi76XzS620KpdSWKgXoFOjBTUkKPt3LAaBpPpfzN+KRmRGdM6RETJFgmqZhQ35rGnHdLpGlh8zTA1eQhNG3UW0J/sjia+NjGFaxGnRsxpsz8loFl2xaLzQhyFP7XzIqRzwPTdoBOISYXxN/2zYPGAmVkixXJ07z7THgIaon8x28jSRJCspTFBz0S0Y+DzFXP/pfQT+H6Vq4h7Xeq6L/OXCYbi1qPCI+h+5wBHRk4lrkCIh3Z70BINOwe22WZWZlMRCdq7Z8nvk4rRFVpcOfSZyu8uamVUTZrIIxb8PQLUyQdhRCOqHOONJCAU26kaCo7eJUwebq0Nl7Ntpf/0fGDggcla2kSoI0BcWeV1+CvtzQ3ojemjEBrpzJDPpmdroONEvIcb7YopEvxa9LIwzaNdm9k=
  - secure: xI1Grh2TMeIPjZcugcs+AN5H6jNnR0rkhA6AmR1C2ipX3AVgkQGCx+Syj/5GikLYpAp/+/UAZ0elp2JubmIZy3L61QmaUufVYSNMmR7FvX/iSingejyGi8plcpKzKgBv1GxxllaWHuhQuKFxzfGoxj5/eCTSKDF5f+TNyP1i82dj2RvTOH1RvC+WK/RkGjHNMg1SXOebwCZreSEtnvMRfBspRCex5XUuImgs4rCNjfmsP9kdLii1i0Rne2eglKee/FnODJkmY/sKJ8lbzActgSashB6Te2U842tNpfmzUeznWPG5obYSc5PsugFDL4lcxPOtJRRTED+8DjkY/GgqDDUt9wfkW2bg0i0XuGSUVOVk+UUy/K1GlJLZ6yrOvVpTe8sVKH7Nu4b3uWo9+zLGLpxjTFIwJPGgY6afiyxaoecZJ5Y7u1bMNxrAjGVSk89qpToJSaiFT/rxToBtAFhfKvtA/3IDrSF4Y39Kt+tdFk0xIrJYbC6TwaaMGcTMeB0GyjcmDuL0HfF68QpMNU8n+PTPKff5oLgQ6A4/pMA1GaEt7U3eebUt7T08cn0w1pEEWGKx8jZiXP4gHGdqup/inspzvmnFn188dFPfnyCcq5OEK1FTPiN6Xb0yd03IxM26GveNTgbFbuPF0t3WBR1EmAjHFuEZKkMcGhuIuhrxO2A=
